{%set name = "docx2txt" %}
{%set version = "0.7" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "335363e5eb827dde2838fae69f5032b9a5c00f311def4022c196424bce697f0f" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - docx2txt

  commands:
    - docx2txt -h

about:
  home: https://github.com/ankushshah89/python-docx2txt
  license: MIT
  # license_file: LICENSE.txt - no MANIFEST.in in source; see https://github.com/ankushshah89/python-docx2txt/pull/8
  license_family: MIT
  summary: 'A pure python-based utility to extract text and images from docx files.'
  dev_url: https://github.com/ankushshah89/python-docx2txt

extra:
  recipe-maintainers:
    - pmlandwehr
    - nikicc
