{% set name = "docx2txt" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/docx2txt-{{ version }}.tar.gz
  sha256: 2c06d98d7cfe2d3947e5760a57d924e3ff07745b379c8737723922e7009236e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - docx2txt
  commands:
    - pip check
    - docx2txt -h
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ankushshah89/python-docx2txt
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: 'A pure python-based utility to extract text and images from docx files.'
  dev_url: https://github.com/ankushshah89/python-docx2txt

extra:
  recipe-maintainers:
    - pmlandwehr
    - rxm7706
    - nikicc
